import img from '@/images/market/marketplace/monster_1.png';
import img2 from '@/images/market/marketplace/monster_2.png';
import author from '@/images/home/team/jack.png';

export const dataTab = [
  {
    id: 1,
    title: 'Live Auctions',
  },
  {
    id: 2,
    title: "Today's Picks",
  },
  {
    id: 3,
    title: 'Land',
  },
  {
    id: 4,
    title: 'Items',
  },
];

export const dataPanel = [
  {
    id: 1,
    dataContent: [
      {
        id: 1,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 2,
        img: img,
        title: 'Hamlet Comtemplates... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Freddie Carpeter',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 3,
        img: img,
        title: 'Loving Vase 01 by Lanza... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 4,
        img: img,
        title: 'Triumphant awakening... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 5,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 6,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 7,
        img: img,
        title: 'Hamlet Comtemplates... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Freddie Carpeter',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 8,
        img: img,
        title: 'Loving Vase 01 by Lanza... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 9,
        img: img,
        title: 'Triumphant awakening... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 10,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 11,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 12,
        img: img,
        title: 'Hamlet Comtemplates... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Freddie Carpeter',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 13,
        img: img,
        title: 'Loving Vase 01 by Lanza... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 14,
        img: img,
        title: 'Triumphant awakening... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 15,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 16,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 17,
        img: img,
        title: 'Hamlet Comtemplates... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Freddie Carpeter',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 18,
        img: img,
        title: 'Loving Vase 01 by Lanza... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 19,
        img: img,
        title: 'Triumphant awakening... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 20,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
    ],
  },
  {
    id: 2,
    dataContent: [
      {
        id: 1,
        img: img2,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 2,
        img: img2,
        title: 'Hamlet Comtemplates... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Freddie Carpeter',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 3,
        img: img2,
        title: 'Loving Vase 01 by Lanza... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 4,
        img: img2,
        title: 'Triumphant awakening... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 5,
        img: img2,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 6,
        img: img2,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 7,
        img: img,
        title: 'Hamlet Comtemplates... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Freddie Carpeter',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 8,
        img: img,
        title: 'Loving Vase 01 by Lanza... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 9,
        img: img,
        title: 'Triumphant awakening... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 10,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
    ],
  },
  {
    id: 3,
    dataContent: [
      {
        id: 1,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 2,
        img: img,
        title: 'Hamlet Comtemplates... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Freddie Carpeter',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 3,
        img: img,
        title: 'Loving Vase 01 by Lanza... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 4,
        img: img,
        title: 'Triumphant awakening... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 5,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 6,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 7,
        img: img,
        title: 'Hamlet Comtemplates... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Freddie Carpeter',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 8,
        img: img,
        title: 'Loving Vase 01 by Lanza... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 9,
        img: img,
        title: 'Triumphant awakening... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 10,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
    ],
  },
  {
    id: 4,
    dataContent: [
      {
        id: 1,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 2,
        img: img,
        title: 'Hamlet Comtemplates... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Freddie Carpeter',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 3,
        img: img,
        title: 'Loving Vase 01 by Lanza... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 4,
        img: img,
        title: 'Triumphant awakening... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 5,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 6,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 7,
        img: img,
        title: 'Hamlet Comtemplates... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Freddie Carpeter',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 8,
        img: img,
        title: 'Loving Vase 01 by Lanza... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 9,
        img: img,
        title: 'Triumphant awakening... ',
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
      {
        id: 10,
        img: img,
        title: "Flame Dress' by Balmain... ",
        tags: 'bsc',
        imgAuthor: author,
        nameAuthor: 'Tyler Covington',
        price: '4.89 ETH',
        wishlist: '100',
      },
    ],
  },
];

export const filterCate = [
  {
    title: 'Categories',
    content: [
      {
        field: 'Art',
        checked: 'checked',
      },
      {
        field: 'Music',
        checked: '',
      },
      {
        field: 'Domain Names',
        checked: '',
      },
      {
        field: 'Virtual Worlds',
        checked: '',
      },
      {
        field: 'Trading Cards',
        checked: '',
      },
      {
        field: 'Collectibles',
        checked: '',
      },
      {
        field: 'Sports',
        checked: '',
      },
      {
        field: 'Utility',
        checked: 'checked',
      },
    ],
  },
  {
    title: 'File Types',
    content: [
      {
        field: 'Image',
        checked: 'checked',
      },
      {
        field: 'Video',
        checked: '',
      },
      {
        field: 'Audio',
        checked: '',
      },
    ],
  },
  {
    title: 'Currencies',
    content: [
      {
        field: 'BNB',
        checked: 'checked',
      },
      {
        field: 'BUSD',
        checked: '',
      },
      {
        field: 'ETH',
        checked: '',
      },
    ],
  },
];
